# Generated by Django 3.1.2 on 2021-08-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formautofiller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdiscussionteacher',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
