# Generated by Django 3.1.2 on 2020-10-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formautofiller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Enter your student id', max_length=9, primary_key=True, serialize=False),
        ),
    ]
