# Generated by Django 3.1.2 on 2020-10-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formautofiller', '0002_auto_20201019_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Enter your student id', max_length=9, unique=True),
        ),
    ]
