# Generated by Django 3.1.2 on 2020-10-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formautofiller', '0004_auto_20201019_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='preference',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
